In [6]:
import pandas as pd
import re
import unicodedata

df = pd.read_csv(
    "amazon_kozmetik_data.csv",
    encoding="utf-8-sig"
)

In [7]:
df.head()

,asin,title,price,old_price,rating,review_count,sales_last_month,link
0,B0BJ7F5XJS,Golden Rose Longstay Liquid Matte Lipstick No:...,355.00,355.00,NaN,NaN,NaN,NaN
1,B0DN29JGN2,Note Cosmetics 3 in 1 Healthy Skin Tinted Mois...,284.90,284.90,3.9,32.0,50.0,NaN
2,B0CB8KW5PH,Note Cosmetics Collagen Concealer 01 Kolajen İ...,350.95,350.95,4.0,28.0,NaN,NaN
3,B0855963RQ,Note Cosmetics Mineral Concealer 202 SPF 15 Gö...,254.90,254.90,4.4,74.0,NaN,NaN
4,B0078MF1PC,L'Oreal Paris Telescopic Maskara - Siyah,499.00,499.00,4.3,13.0,500.0,NaN

In [8]:
df.shape

(251, 8)

In [9]:
df.columns

Index(['asin', 'title', 'price', 'old_price', 'rating', 'review_count',
       'sales_last_month', 'link'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   asin              251 non-null    object
 1   title             251 non-null    object
 2   price             251 non-null    float64
 3   old_price         167 non-null    float64
 4   rating            204 non-null    float64
 5   review_count      204 non-null    float64
 6   sales_last_month  43 non-null     float64
 7   link              0 non-null      float64
dtypes: float64(6), object(2)
memory usage: 15.8+ KB

In [11]:
print("\nEksik değerler:")
print(df.isnull().sum())

Eksik değerler:
asin                  0
title                 0
price                 0
old_price            84
rating               47
review_count         47
sales_last_month    208
link                251
dtype: int64

In [12]:
print("\nTekrarlı kayıt sayısı:")
print(df.duplicated().sum())

Tekrarlı kayıt sayısı:
0

In [13]:
df = df.drop(
    columns=[
        "asin",
        "link"
    ],
    errors="ignore"
)

print(df.head())
print(df.columns)

                                               title   price  old_price  \
0  Golden Rose Longstay Liquid Matte Lipstick No:...  355.00     355.00
1  Note Cosmetics 3 in 1 Healthy Skin Tinted Mois...  284.90     284.90
2  Note Cosmetics Collagen Concealer 01 Kolajen İ...  350.95     350.95
3  Note Cosmetics Mineral Concealer 202 SPF 15 Gö...  254.90     254.90
4           L'Oreal Paris Telescopic Maskara - Siyah  499.00     499.00

   rating  review_count  sales_last_month
0     NaN           NaN               NaN
1     3.9          32.0              50.0
2     4.0          28.0               NaN
3     4.4          74.0               NaN
4     4.3          13.0             500.0
Index(['title', 'price', 'old_price', 'rating', 'review_count',
       'sales_last_month'],
      dtype='object')

In [14]:
old_price_mean = df["old_price"].mean()

print("Old Price Ortalama:", old_price_mean)

df["old_price"] = np.where(
    df["old_price"].isna(),
    np.maximum(old_price_mean, df["price"]),
    df["old_price"]
)

Old Price Ortalama: 485.8617964071857

In [15]:
same_price_count = (
    df["price"] == df["old_price"]
).sum()

print(
    "Price = Old Price olan kayıt:",
    same_price_count
)

Price = Old Price olan kayıt: 126

In [16]:
df["discount_rate"] = (
    (df["old_price"] - df["price"])
    / df["old_price"]
) * 100

In [17]:
print(df.isnull().sum())

title                 0
price                 0
old_price             0
rating               47
review_count         47
sales_last_month    208
discount_rate         0
dtype: int64

In [18]:
rating_mean = df["rating"].mean()

review_mean = df["review_count"].mean()

print("Rating Ortalama:", rating_mean)
print("Review Ortalama:", review_mean)

df["rating"] = df["rating"].fillna(rating_mean)

df["review_count"] = df["review_count"].fillna(review_mean)

Rating Ortalama: 4.258333333333333
Review Ortalama: 102.33823529411765

In [19]:
print(df[["rating", "review_count"]].isnull().sum())

rating          0
review_count    0
dtype: int64

In [20]:
mask = df["sales_last_month"].isna()

df.loc[mask, "sales_last_month"] = np.random.randint(
    50,
    501,
    size=mask.sum()
)

In [21]:
print(df["sales_last_month"].isnull().sum())

0

In [22]:
unique_titles = df["title"].dropna().unique()

for i, title in enumerate(unique_titles, start=1):
    print(f"{i}. {title}")

print("\n" + "="*50)
print("Toplam eşsiz title sayısı:", len(unique_titles))

1. Golden Rose Longstay Liquid Matte Lipstick No: 42 - Bulaşmayan Kalıcı Likit Mat Ruj
2. Note Cosmetics 3 in 1 Healthy Skin Tinted Moisturizer Renk Ton Eşitleyici 50 SPF Aydınlatıcı Krem
3. Note Cosmetics Collagen Concealer 01 Kolajen İçerikli SPF 20 Göz Altı Kapatıcısı
4. Note Cosmetics Mineral Concealer 202 SPF 15 Göz Altı Kapatıcısı
5. L'Oreal Paris Telescopic Maskara - Siyah
6. Blistex Medplus Stick Kuru ve Çatlamış Dudaklara Onarıcı ve Ferahlatıcı Dudak Bakım Kremi SPF 15
7. Cream Co. Su Bazlı Moisturizer Nemlendirici Aydınlatıcı Yüz Kremi, Hyaluronik Asit, 50 ML, Tüm Cilt Tipleri
8. The Purest Solutions, Gözenek ve Siyah Nokta Görünümünü Azaltmaya Yardımcı Arındırıcı Tonik,%5 Glikolik Asit, AHA, BHA, 200 ml
9. L'Oreal Paris Elseve Mucizevi Yağ Saç Güzelleştirici Krem 150 ml - Kuru ve Sert Saçlar İçin
10. L'Oreal Paris Lumi Blush Likit Allık - 630 Glowy True Rose
11. The Purest Solutions, Retinol İçerikli Gece Bakım Serumu, Kırışıklık Karşıtı Bakım, 30 ml (%1 Retinol + Seramid)
12. Maybelline New York Lash Sensational Sky High Maskara
13. L'Oreal Paris Elseve Glycolic Gloss Parlaklığı Saça Mühürleyen Laminasyon 5 Dakikada Durulanan Bakım 200 ml
14. L'Oreal Paris Panorama Hacim Veren Maskara - Siyah
15. NIVEA Böğürtlen Dudak Bakım Kremi 4.8 gr, 24 Saat Nemlendirme,Böğürtlen Kokusu,Işıltılı Renk,Mineral Yağı İçermez
16. La Roche-Posay Cicaplast Baume B5+ 40ml
17. Cream Co. Allık Ruj Göz Farı Glow Tint Soft Mocha, Nemlendirici Makyaj, 504 Nude, Hyaluronik Asit Peptit
18. URBAN Care Twisted Curls Hibiscus & Shea Butter Kıvırcık ve Dalgalı Saçlara Özel Durulanmayan Bakım Kremi 175 ml- Vegan
19. The Purest Solutions, C Vitamini Aydınlatıcı ve Cilt tonu Eşitleyici Cilt Bakım Serumu 30 ml (%10 Ascorbic Acid & Ferulic Acid%0,5)
20. Sheer Up Yarı Transparan & Parlak Bitişli Nemlendirici Ruj
21. Note Cosmetics Flawless Lipgloss 03 Dried Rose Nemlendirici Etkili Parlak Ruj, Pembe
22. Golden Rose Longstay Liquid Matte Lipstick No: 37 - Bulaşmayan Kalıcı Likit Mat Ruj
23. Note Cosmetics BB Concealer 03 SPF 15 Göz Altı Kapatıcısı
24. Note Cosmetics Hydramoist Lipgloss 07 Mellow Thought Nemlendirici Dudak Parlatıcısı, Pembe
25. Dove Beauty Cream Bar Katı Güzellik Sabunu Original Nemledirici Etkili, 90 g
26. Golden Rose Emily Long Lasting Lip Pencil No: 203 - Uzun Süre Kalıcı Dudak Kalemi
27. Cream Co. Allık Ruj Göz Farı Glow Tint Warm Peach, Nemlendirici Makyaj, 503 Şeftali, Hyaluronik Asit Peptit
28. URBAN Care Style Guide Doğal ve Mat Görünüm Sağlayan Esnek Tutuşlu Wax 100 ml- Vegan
29. Cream Co. Cloud Moisturizer, Hassas Ciltler için Nemlendirici Yüz Kremi, 50 ml
30. L'Oreal Paris Glotion All-In-One Doğal Işıltı Aydınlatıcı Losyon - 902 Light Glow
31. Maybelline New York Lash Sensational Yelpaze Etkili Intense Black Maskara - Ekstra Siyah 1 Paket (1 x 9.5 ml)
32. The Purest Solutions, Leke Karşıtı ve Leke Görünümü Önleyici Arbutin Cilt Bakım Serumu 30 ml (Arbutin%2 + Hyaluronic Acid)
33. Pastel Plump Up Gloss 202 Loverdose Dolgunlaştırıcı Dudak Parlatıcısı
34. La Roche-Posay Anthelios Oil Control Fluid SPF 50+ Akışkan Yüz Güneş Kremi 50 ml
35. Pastel Cream Blush - Krem Allık, 42 Rosery, 3.6 g
36. Cream Co. Allık Ruj Göz Farı Glow Tint Rich Berry, Nemlendirici Makyaj, 502 Bordo, Hyaluronik Asit Peptit
37. The Purest Solutions, Gözenek ve Siyah Nokta Karşıtı, Sivilce Önleyici Niacinamide Cilt Bakım Serumu 30 ml (Niacinamide 5% & Zinc Pca 1%)
38. Maybelline New York Instant Anti Age Eraser Kapatıcı, 01 Light, 6.8 ml
39. Maybelline New York Super Lock Brow Glue Kaş Sabitleyici Maskara
40. 50+ SPF Korucuyu Yüz ve Vücut Güneş Kremi 50 ml
41. CeraVe Moisturising Cream Nemlendirici Bakım Kremi 50 ml
42. Yumuşak Dokulu, Dökülme Yapmayan 3 Renkli Göz Farı Triple Shadow No.20 (Vintage Coin)
43. The Purest Solutions, AHA & BHA Canlandırıcı & Cilt Tonu Eşitleyici Kırmızı Peeling Cilt Bakım Serumu 30 ml (Aha 10% + Bha 2%)
44. Golden Rose Max Hold Brow Glue - Şeffaf Kaş Sabitleyici Jel (Biotin & B5 İçerikli)
45. Neutrogena Norveç Formülü Besleyici Çok Amaçlı Yoğun Bakım Kremi, 300 Ml
46. Maybelline New York Instant Anti Age Eraser Kapatıcı, 00 Ivory, 6.8 ml
47. L'Oreal Paris Glow Paradise Balm-in-Lipstick Işıltı Veren Ruj 112 Pastel Exaltation
48. L'OREAL PARIS Yaş Uzmanı 65+ Kırışıklık Karşıtı Besleyici Krem
49. Golden Rose Roll On Lipgloss - 01 Strawberry - Çilek Aromalı Dudak Parlatıcısı
50. Golden Rose Emily Waterproof Eye Pencil No: 101 - Suya Dayanıklı Göz Kalemi
51. Maybelline New York Lifter Gloss Nemlendirici Dudak Parlatıcısı - 003 Moon
52. L'Oreal Paris Infaillible 24H Brow Lamination Şeffaf Kaş Sabitleyici
53. Maybelline New York Lifter Gloss Nemlendirici Dudak Parlatıcısı - 005 Petal
54. Golden Rose Velvet Matte Lipstick No:34
55. Note Cosmetics Matte Queen Lipstick 24 Ravishing Rose Kalıcı Likit Ruj, Nude
56. Note Cosmetics Hydramoist Lipgloss 12 Magic Touch Nemlendirici Dudak Parlatıcısı, Işıltılı
57. Note Cosmetics Hydramoist Lipgloss 24 Smell Of Coffee Nemlendirici Dudak Parlatıcısı, Nude
58. Youth Serum
59. Anti Aging Elixir
60. L'Oreal Paris Yaş Uzmanı 50+ Kırışıklık Karşıtı Yenileyici Krem
61. Clasy Care Göz Altı Kremi – Morluk ve Şişlik Karşıtı –%5 Kafein +%2 Hyalüronik Asit – Kırışıklık, Torba ve İnce Çizgiler için Aydınlatıcı Göz Kremi – Kore Esintili Göz Çevresi Kremi, 40 ml
62. Dove Beauty Cream Bar Pink Nemlendirici Krem 90 g
63. L'Oreal Paris Revitalift Clinical Anında Aydınlatıcı C Vitamini Serum Etkili Maske
64. L'Oreal Paris Color Riche Saten Bitişli Ruj - 570 Worth It Intense
65. MISSHA 48 Saat Kalıcı Saten Fondöten 15ml SPF50+ Radiance Perfect Fit Cushion Foundation No.21/Fair
66. Golden Rose Nude Look Perfect Matte Lips Ruj No:01 Coral Nude
67. Kiss Me More Yüksek Pigmentli & Mat Bitişli Nemlendirici Likit Ruj
68. Golden Rose Glow Kiss Tinted Lip Balm No: 03 Berry Pink - Renkli Dudak Nemlendiricisi SPF15
69. Maybelline New York Sunkisser Likit Allık- 08 Shades On
70. Baked Blush-On Yüksek Pigmentli & Mat Bitişli Fırınlanmış Allık
71. Cream Co. Dudak Parlatıcısı Nemlendirici Besleyici Lip Oil Gloss, Dudak Yağı, Ahududu Aromalı, E Vitamini
72. Gabrini Eye Max Eyebrow Pencil 4
73. L'Oreal Paris Glotion All-In-One Doğal Işıltı Aydınlatıcı Losyon - 904 Deep Glow
74. L'Oreal Paris Panorama Hacim Veren Maskara - Koyu Kahverengi
75. Pierre Cardin Staylong Lipcolor-Kissproof – Uzun Süre Kalıcı Lipgloss-5 ml- Chic Berry-360
76. Note Cosmetics Collagen Concealer 02 Kolajen İçerikli SPF 20 Göz Altı Kapatıcısı
77. Maybelline New York Color Sensational Powder Matte Ruj, 15 Smoky Taupe, Nude
78. MISSHA Siyah Nokta Karşıtı Makyaj Temizleme Yağı 100ml Super Off Cleansing Oil (Blackhead Off)
79. Golden Rose Emily Long Lasting Lip Pencil No: 211 - Uzun Süre Kalıcı Dudak Kalemi
80. Golden Rose Lipstick No: 57 - Nemlendirici Etkili Kremsi Ruj
81. Golden Rose Dream Lips Lipliner No: 503 - Mat Bitişli Yumuşak Dudak Kalemi
82. Maybelline New York Lifter Gloss Honey’d Nemlendirici Dudak Parlatıcısı - 29 Toast
83. Golden Rose Brow Color Tinted Eyebrow Mascara No: 02 Light Brown - Fiber İçerikli Kaş Maskarası
84. Pierre Cardin Staylong Lipcolor-Kissproof – Uzun Süre Kalıcı Lipgloss-5 ml-Paparazzi Pembe-352
85. L'Oreal Paris Color Riche Intense Volume Matte Ruj - 550 Nude Unapologetic
86. Mara Kozmetik IMM209.363 Saç Maskarası Açık Kumral
87. L'Oreal Paris Pro XXL Lift Çift Taraflı Maskara - Kirpik Lifting Etkisi
88. CLASYCARE Radiant Göz Çevresi Serumu – Kafein Göz Serumu – Hyaluronik Asit ve C Vitamini ile Göz Altı Morlukları, Şişlik ve İnce Çizgilere Karşı Etkili – Tüm Cilt Tipleri İçin, 50 ml
89. Golden Rose Yumuşak ve Mat Kremsi Lipcolor No:106 1 Paket
90. Golden Rose Nude Look Natural Shine Lipgloss No: 01 Nude Delight - Doğal Parlak Dudak Parlatıcısı
91. Jane Iredale HydroPure Hyaluronic Dudak Parlatıcı
92. Quality Life Göz Altı Morluk, Torbalanma, Kırışıklık, Koyu Halka ve Aydınlatıcı Göz Çevresi Kafein Serumu
93. Jane Iredale Beyond Matte Liquid Foundation, Likit Mat Fondöten (M4, 27 ml)
94. Flormar Yağlı & Karma Ciltlere Özel Parlama Önlemeye Yardımcı SPF25 Mat Bitişli BB Krem 003 LIGHT
95. Doa Kozmetik Laktik Asit AHA Tonik%10 laktik asit (%10 Lactic Acid)
96. Pastel Eye Cream + Hydrating Satin Concealer - Göz Kremi + Göz Altı Kapatıcısı, 66 Deep Medium, 4,3 ml
97. CLASYCARE Aydınlatıcı Yüz Toniği – Hyaluronik Asitli Nemlendirici Leke Karşıtı – Sivilce İzleri İçin Tonik – Hassas ve Yağlı Ciltler İçin Nazik Bakım – Gözenek Sıkılaştırıcı Cilt Ürünü, 200 ml
98. CLASYCARE Kil Maskesi – Gözenek Sıkılaştırıcı ve Derinlemesine Temizleyici Yüz Maskesi | Siyah Nokta Karşıtı | Yağ Dengeleyici | Nemlendirici & Doğal İçerikli, 100 ml
99. Show By Pastel Monochrome Eyeshadow 26 - Sand Dunes
100. Golden Rose Tattoo Gel Eyepencil No: 104 Glitzy Brown - 24 Saat Kalıcı Suya Dayanıklı Jel Göz Kalemi
101. Gabrini Terracotta Blush On Allık (No: 31)
102. Maybelline New York Master Drama Lightliner Göz Kalemi, 25 Glimmerlight Pink, Metalik Açık Pembe
103. Cream Co. Likit Bronzer Glow Sculpt Eclipse, Kontür Nötr Koyu Kahve, Yüz Şekillendirici Nemlendirici Makyaj
104. Water Lip Stain Su Bazlı & Kalıcı Dudak Renklendiricisi
105. Golden Rose Silky Touch Compact Powder No: 08 Soft Caramel - İpeksi Sıkıştırılmış Pudra 12 g
106. Doa Kozmetik Bha Tonik%2 Salisilik Asit (Salicylic Acid)
107. MISSHA C Vitamini İçerikli Leke Karşıtı Günlük Yaprak Maske Vita C Plus Daily Toning Mask
108. Doa Kozmetik Retinal%0,025 Krem
109. MISSHA Yoğun Esanslı Kalıcı Saç&Vücut Spreyi 105ml Dare Body Mist (Fresh Grapefruit)
110. Pink Edt 100 ml Kadın Parfüm Niche Serisi
111. Doa Kozmetik Retinal%0,05 Krem
112. Doa Kozmetik L-Ascorbic Acid Serum Saf C Vitamini Serumu
113. Doa Kozmetik C Vitamini%10 Serum
114. W-Lab Kozmetik Ayak ve Tırnak Bakım Spreyi 100 Ml
115. Golden Rose Velvet Matte Lipstick No: 03 - Yoğun Pigmentli Kadifemsi Mat Ruj
116. Doa Kozmetik Bha Yüz Yıkama Jeli
117. Mara Kozmetik French Manikür Kalemi Siyah
118. NIVEA MEN Erkek Deep Dimension Duş Jeli 500 ml,Derinlemesine Temizlik,Bakımlı Cilt,Vücut,Yüz ve Saç İçin,Ferah Koku,Aktif Karbon (2 paketi)
119. SEYAHAT KİTİ-4'LÜ DOLDURULABİLİR ŞİŞE SETİ + KOZMETİK KUTU-1
120. Nascita 2'li Mini Makyaj Süngeri Fondöten + BB Krem
121. Doğal ve Endüstriyel Kozmetik Formülleri
122. BEE BEAUTY SİYAH NOKTA KARŞITI TEMİZLEME BANDI AKTİF KARBON İÇERİKLİ - NOSE PORE STRIPS CHARCOAL
123. Peluş Yumuşacık Makyaj Çantası - Kozmetik Organizeri (Krem)
124. Seyahat Tipi Bölmeli Makyaj Kozmetik Çantası Organizer (Mor)
125. NIVEA Güneş Koruyucu & Nemlendirici Sprey GKF50 200 ml + NIVEA Soft 75 ml el kremi
126. Bioworld Tuvalet Kozmetik Seti, Hello Kitty Face AOP Kırmızı, OSFA
127. Lux Kozmetik Makyaj Çubuğu, Pamuklu Kozmetik Temizleme Çubukları, 80 Adet
128. wellLineSeyahat Kiti-4'lü Doldurulabilir Şişe Seti + Kozmetik Kutu
129. Lüks Lacivert Kot Makyaj ve Kozmetik Seyahat Çantası
130. Seyahat Şişesi Seti 6 Parça(5 Dolum Kabı + 1 Taşıma Çantası) – Uçak Kabin Uyumlu Dolum Şişeleri, Şampuan, Krem ve Kozmetik Taşıma Seti, Sızdırmaz Kapaklı, Şeffaf Çantalı (Krem Renk)
131. Makyaj Çantası Sert Kapaklı Kozmetik Seyahat Organizeri Çok Amaçlı Siyah
132. Kozmetik Traş Aleti
133. 2 Katlı Makyaj Organizeri Kozmetik Aksesuar Düzenleyici Kozmetik Vitrini (Duman Gri)
134. SHANY Kozmetik Şeffaf Makyaj Çantası, Omuz Askılı Pro Mua Yuvarlak Çanta, Büyük
135. Kadın Kozmetik El Çantası Fermuarlı Love Moschino JC5310PP1IK2200A
136. Av A Dos Erkek Siyah Vegan Deri Tıraş Seyahat Kozmetik Portföy Bakım El Çanta Günlük
137. Eynel Şeffaf Makyaj Malzemesi Organizer Büyük Kristal Makyaj Masası Organizatörü Kozmetik Düzenleme Kutusu Güzellik Malzemesi Düzenleyici (Çekmeceli Model)
138. The Make-up Manual: Your Beauty Guide for Brows, Eyes, Skin, Lips and More
139. Makyaj Çantası Sert Kapaklı Kozmetik Seyahat Organizeri Çok Amaçlı Mavi
140. 3 Katlı Makyaj Organizeri Kozmetik Aksesuar Düzenleyici Kozmetik Vitrini (Duman Gri)
141. Guerlain Terracotta Matte Sculpting Powder Moyen Medium Pudra
142. COTPOLY Polipropilen Kadın Makyaj Valizi, Askılı Kozmetik Organizer El Valizi, Sert Gövdeli Seyahat Beauty Case, Geniş Hacimli Makyaj Çantası (Siyah)
143. Erkek Kozmetik Makyaj Tıraş Çantası Erkek El Çantası (Kahverengi)
144. COTPOLY Polipropilen Kadın Makyaj Valizi, Askılı Kozmetik Organizer El Valizi, Sert Gövdeli Seyahat Beauty Case, Geniş Hacimli Makyaj Çantası (Su Yeşili)
145. Ecoform Su Geçirmez Organizer Askılı Seyahat Kozmetik Makyaj Çantası Mint
146. Makyaj Seyahat Çantası Bavul Düzenleyici Makyaj Bavulu Çanta Kozmetik Bakım Çantası (MAVİ)
147. Seyahat Kiti-6'lı Doldurulabilir Şişe Seti Kozmetik Kutu
148. Hava Pompalı Doldurulabilir Vakumlu Krem,Fondoten Sıvı Kozmetik Ürün Şişesi
149. Deri Makyaj Kozmetik Çantası Seyahat Tipi Çanta Organizer (Gri)
150. Afracam Mini Şeffaf Cam Kavanoz, 10 ml Hacimli, Sızdırmaz Aynalı Kapaklı, Krem ve Kozmetik Saklama Kutusu, Lip Balm 48 Adet
151. 2 Katlı Makyaj Organizeri Kozmetik Aksesuar Düzenleyici Kozmetik Vitrini Yuvarlak (Zümrüt Yeşil)
152. Ecoform Su Geçirmez Organizer Askılı Seyahat Kozmetik Makyaj Çantası Somon
153. 7 Bölmeli Kapaklı Makyaj Organizeri, Fırça Düzenleyici, Toz Geçirmez Şeffaf Kapaklı Kozmetik Kutusu, Masaüstü Organizer (Vizon)
154. United Colors of Benetton Unisex Yetişkin Kozmetik Çantası, Siyah, Seyahat Çantası 9 İnç
155. United Colors of Benetton Unisex Yetişkin Kozmetik Çantası, Mor, Seyahat Çantası 9 İnç
156. Ecoform Su Geçirmez Organizer Askılı Seyahat Kozmetik Makyaj Çantası Bordo Çiçekli
157. MYPOLO Bilbao Kırılmaz PP Şifreli Makyaj Çantası, Valiz Üstü, Omuz Askılı, Kozmetik ve Seyahat El Valizi (Rose)
158. Ecoform Su Geçirmez Organizer Askılı Seyahat Kozmetik Makyaj Çantası Bordo Düz
159. Nascita Kas Makası
160. Nascita Toz & Sıvı Yapılı Ürünlere Uygun Renkli Dikdörtgen Makyaj Süngeri
161. Makyaj Çantası Sert Kapaklı Kozmetik Seyahat Organizeri Pembe
162. Makyaj Organizeri Kozmetik Aksesuar Düzenleyici Kozmetik Vitrini (Duman Gri)
163. Makyaj Çantası | Makeup Bag | Kapitone Bakım Seyahat Kozmetik Çantası (Beyaz-Pembe)
164. Deri Makyaj Kozmetik Çantası Seyahat Tipi Çanta Organizer (Şeftali)
165. HOMENIVA Büyük Boy Çekmeceli Kozmetik Makyaj Malzemeleri Organizeri
166. Makyaj Organizeri Kozmetik Aksesuar Düzenleyici Kozmetik Vitrini Yuvarlak (Zümrüt Yeşil)
167. El Tutmalı Büyük Boy Mavi Şeffaf Tatil Plaj Kozmetik Makyaj ve Bakım Çantası
168. Ecoform Su Geçirmez Organizer Seyahat Kozmetik Makyaj Çantası Lacivert
169. 3 Katlı Makyaj Organizeri Kozmetik Aksesuar Düzenleyici Kozmetik Vitrini Yuvarlak (Duman Gri)
170. Şeffaf Çift Bölmeli Seyahat Kozmetik Makyaj Çantası (30 * 22 * 16 CM EBATLARINDA)
171. Makyaj Çantası Kozmetik Düzenleyici Seyahat Tipi Deri Görünümlü Şeffaf Organizer (24 * 18 * 11 cm) (eflatun)
172. Ecoform Su Geçirmez Organizer Seyahat Kozmetik Makyaj Çantası Gri
173. Ecoform Su Geçirmez Organizer Askılı Seyahat Kozmetik Makyaj Çantası Kahverengi
174. Makyaj Çantası | Makeup Bag | Kapitone Bakım Seyahat Kozmetik Çantası (Yeşil)
175. Afracam Mini Amber Cam Kavanoz, 10 ml Hacimli, Sızdırmaz Kapaklı, Krem ve Kozmetik Saklama Kutusu, Lip Balm 6 Adet
176. Ecoform Su Geçirmez Organizer Seyahat Kozmetik Makyaj Çantası Pembe Kiraz Desenli
177. Ecoform Su Geçirmez Organizer Seyahat Kozmetik Makyaj Çantası Somon
178. Çantalı Seyahat Seti – Renkli Şeffaf Doldurulabilir Şişe ve Krem Kabı – Uçak ve El Bagajı Uyumlu
179. Afracam 50 ml Cam Kozmetik Kavanoz Şeffaf 50 cc Yassı Krem Kavanozu Metal Gümüş Kapaklı 6 Adet
180. Ecoform Su Geçirmez Organizer Askılı Seyahat Kozmetik Makyaj Çantası Turuncu
181. Su Geçirmez Makyaj Çantası Sert Kasa Kilitli Kozmetik Valizi Darbeye Dayanıklı Seyahat Çantası Organizer 30x23x16 cm Ayı Desenli Ekru
182. Streak Seyahat Makyaj Kozmetik Çantası Taşınabilir Çanta Organizatörü Çok Fonksiyonlu PEMBE
183. Seyahat El Çantası Siyah Traş Kozmetik Çanta
184. Ecoform Su Geçirmez Organizer Askılı Seyahat Kozmetik Makyaj Çantası Gri
185. Wiforte Şeffaf Makyaj Çantası - Makyaj Malzemesi Düzenleyici, Sütyen ve İç Çamaşır Organizeri, Kozmetik Malzemesi Saklama Çantası (Yeşil)
186. Boldy Erkek Kozmetik Çantası-Tıraş Çantası-Seyahat Çantası-Makyaj Çantası-Traş-El Çantası-Handbag
187. Deri Erkek Bakım Çantası Seyahat Organizeri – Tıraş Çantası, Kişisel Bakım ve Kozmetik Düzenleyici, Fermuarlı Geniş Hacimli Dopp Kit Siyah
188. Arnee Beyaz Yumuşak Koyun Tüyü Peluş Makyaj Çantası Küçük Kozmetik Çantası (Kahverengi)
189. Deri Erkek Bakım Çantası Seyahat Organizeri – Tıraş Çantası, Kişisel Bakım ve Kozmetik Düzenleyici, Fermuarlı Geniş Hacimli Dopp Kit Kahverengi
190. Boldy Erkek Kozmetik Çantası-Tıraş Çantası-Seyahat Çantası-Makyaj Çantası-Traş Çantası-El Çantası-Handbag
191. Meapuff, 50'li Set 20x30 cm Su Geçirmez Kozmetik ve Plaj Çantası
192. 4 Parça Şeffaf Banyo ve Makyaj Çantası Seti - Antrasit Gri Banyo Lifi, Örgülü Sırt Kesesi ve El Havlusu - Su Geçirmez Unisex Seyahat Organizeri (Washbag)
193. Erkek Hakiki Deri Portföy Clutch Traş Bakım Kozmetik Çantası ve Günlük El Çantası Dopp Kit Kahverengi
194. Pötikareli Keten Yıkanabilir Çıtçıt Detaylı Kadınlar için Ped Çantası,Mini Kozmetik Makyaj Çantası,Ped Kesesi,Cüzdan,Kartlık (yeşil)
195. 4 Adet İç İçe Geçen, Fermuarlı, Takı, Makyaj Çantası Seti, Organize Çanta, Küçük Özel, Kişisel Eşya 4 lü Çanta Seti
196. MYPOLO Bilbao Kırılmaz PP Şifreli Makyaj Çantası, Valiz Üstü, Omuz Askılı, Kozmetik ve Seyahat El Valizi (Kemik)
197. ATA HOME Makyaj,Takı Ve Bakım Ürünleri Organizeri Rafı Standı Büyük boy Makyaj Organizeri İki Katlı Çok Amaçlı Düzenleyici Saklama Seti
198. Pastel Nude Ruj - Nude Ruj 528, 4,3 G
199. Vichy Dercos Energisant Dökülme Karşıtı Bakım Şampuanı
200. Saç Dökülmesine Karşı Geliştirilmiş Patentli İçeriğe Sahip Serum. Procapil + Biotin + Apigenin – Erkek ve Kadınlar İçin Yeni Saç Oluşumunu Destekler – 50 ml
201. Golden Rose Ice Color Nail Lacquer No: 228 - Parlak Bitişli Mini Oje 6 ml
202. Flormar Hero Volume&Curl İnce ve Seyrek Kirpikler için Hacim ve Kıvrım Veren Kıl Fırçalı Maskara No. 000-8682536022804 (3 paketi)
203. Pierre Cardin Color Travel Nails -105, 150 Gr
204. Aputue Makyaj Fırçası Seti, 8 Parça Seyahat Kozmetik Fırça Seti PU Çantalı, Mini Boy Taşınabilir Yumuşak Fondöten Allık Göz Farı Yüz ve Dudak Fırçaları, Kızlar ve Kadınlar İçin (Fildişi Rengi)
205. URBAN Care Hacimlendirici Kuru Şampuan It's So High 200 ml- Vegan (2 paketi)
206. Golden Rose Keratin Nail Color Glitter No: 409 - Keratin İçerikli Güçlendirici Parlak Oje
207. DIAROSSA® W033, NARCISIM FOR HER 'dan esinlenilmiş koku ikizi, 50ml EDP Kadın Parfümü
208. Golden Rose Color Expert Nail Lacquer No: 77 - Geniş Fırçalı Oje 10.2 ml
209. Urban Care Expert No.6 Biotin Caffeine Dökülme Karşıtı Saç Bakım Serumu, 50 Mililitre, Vegan (3 paketi)
210. Golden Rose Wow Nail Color No: 91 - Parlak Bitişli Mini Oje 6 ml
211. MineVital Cherry - Nefes Alan Oje, Breathable, Water Permeable 15 ml (04)
212. Golden Rose Color Expert Nail Lacquer No: 13 - Geniş Fırçalı Oje 10.2 ml
213. Çok Bölmeli Tasarımlı Asılı Tuvalet Çantası, Kuru ve Islak Ayırma için Su Geçirmez Seyahat Kozmetik Düzenleyici, Kancalı Katlanabilir Banyo Saklama Kutusu (Koyu Mavi)
214. Garnier Hydra Bomb Kağıt Maske (6 paketi)
215. Nascita Magical Curl Saç Fırçası - 53 (3 paketi)
216. The Purest Solutions Exfoliating Salicylic Acid Cleanser Temizleyici 400 ml 2li paket
217. L'ORÉAL PARIS True Match Pudra - 6.5.D/6.5.W Golden Toffee
218. Golden Rose Soft Color Matte Mono Eyeshadow No:11 1 Paket
219. Nascita Pro Faux Takma Kirpik
220. Golden Rose Wow Nail Color No: 98 - Parlak Bitişli Mini Oje 6 ml
221. L'Oreal Paris Yaş Uzmanı 40+ Kırışıklık Karşıtı Sıkılaştırıcı Krem (3 paketi)
222. Nascita Magical Curl Saç Fırçası - 54 (3 paketi)
223. CLASYCARE Onarıcı Gözenek Sıkılaştırıcı Yüz Temizleme Jeli – Hassas ve Karma Ciltler İçin Nazik Nemlendirici Yüz Temizleyici, Günlük Yüz Yıkama ve Makyaj Temizleyici, 200 ml
224. Mood Booster Hafif Yapılı & Kremsi Dokulu Likit Aydınlatıcı
225. Nascita Magical Curl Pembe Saç Fırçası - 58 (3 paketi)
226. Illusione Ambre EDP Kadın Parfüm 50ml | Amber-Paçuli-Gül | Bergamot, Sedir, Karanfil, Vetiver
227. Mecitefendi Zeytin Şampuanı, 400 Ml

In [23]:
brand_map = {
    "maybelline": "Maybelline",
    "loreal": "L'Oréal",
    "loreal paris": "L'Oréal",
    "nivea": "Nivea",
    "NIVEA":"nivea",
    "farmasi": "Farmasi",
    "garnier": "Garnier",
    "flormar": "Flormar",
    "pastel": "Pastel",
    "golden rose": "Golden Rose",
    "note cosmetics": "Note Cosmetics",
    "note": "Note Cosmetics",
    "cream co": "Cream Co",
    "la roche posay": "La Roche-Posay",
    "urban care": "URBAN Care",
    "dove": "Dove",
    "neutrogena": "Neutrogena",
    "blistex": "Blistex",
    "the purest solutions": "The Purest Solutions",
    "cerave": "CeraVe",
    "missha": "MISSHA",
    "doa kozmetik": "Doa Kozmetik",
    "clasy care": "Clasy Care",
    "clasycare": "Clasy Care",
    "vichy": "Vichy",
    "vaseline": "Vaseline",
    "gabrini": "Gabrini",
    "nascita": "Nascita",
    "pierre cardin": "Pierre Cardin",
    "bee beauty": "Bee Beauty",
    "doa": "Doa Kozmetik"
}

In [24]:
category_map = {
  
    "ruj": "Makyaj",
    "lipstick": "Makyaj",
    "lipgloss": "Makyaj",
    "gloss": "Makyaj",
    "maskara": "Makyaj",
    "mascara": "Makyaj",
    "eyeliner": "Makyaj",
    "eyeshadow": "Makyaj",
    "allık": "Makyaj",
    "blush": "Makyaj",
    "concealer": "Makyaj",
    "fondöten": "Makyaj",
    "foundation": "Makyaj",
    "brow": "Makyaj",
    "pencil": "Makyaj",
    
    # SKINCARE
    "serum": "Cilt Bakımı",
    "cream": "Cilt Bakımı",
    "moisturizer": "Cilt Bakımı",
    "tonik": "Cilt Bakımı",
    "cleanser": "Cilt Bakımı",
    "mask": "Cilt Bakımı",
    "spf": "Cilt Bakımı",
    "anti aging": "Cilt Bakımı",
    "retinol": "Cilt Bakımı",
    "niacinamide": "Cilt Bakımı",
    "vitamin c": "Cilt Bakımı",
    
    # HAIR CARE
    "shampoo": "Saç Bakım",
    "saç": "Saç Bakım",
    "hair": "Saç Bakım",
    
    # PERFUME
    "parfüm": "Parfüm",
    "edp": "Parfüm",
    "edt": "Parfüm",
    
    # ACCESSORIES
    "çanta": "Aksesuar",
    "organizer": "Aksesuar",
    "fırça": "Aksesuar",
    "brush": "Aksesuar",
    "makyaj çantası": "Aksesuar",
    "set": "Aksesuar",
    "kit": "Aksesuar",
    "bottle": "Aksesuar",
}

In [25]:
def normalize(text):
    if pd.isna(text):
        return ""
    text = text.lower()
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def extract_brand(text):
    text = normalize(text)
    
    for k, v in sorted(brand_map.items(), key=lambda x: -len(x[0])):
        if k in text:
            return v
    return np.nan


def extract_category(text):
    text = normalize(text)
    
    for k, v in category_map.items():
        if k in text:
            return v
    return "Other"


df["clean_title"] = df["title"].apply(normalize)
df["brand"] = df["title"].apply(extract_brand)
df["category"] = df["title"].apply(extract_category)

In [26]:
df[["brand", "category"]].isna().sum()

brand       125
category      0
dtype: int64

In [27]:
df.to_csv("kozmetik_dataset_preprocessing_1.csv", index=False, encoding="utf-8-sig")

In [28]:
df.to_excel("kozmetik_dataset_duzenlenmis.xlsx", index=False, engine="openpyxl")

In [1]:
df = pd.read_excel(
    "kozmetik_dataset_preprocessing_2.xlsx")
print("done")

done

In [2]:
df = df.drop(columns=["brand", "title", "category_extracted"], errors="ignore")

In [3]:
df.columns

Index(['price', 'old_price', 'rating', 'review_count', 'sales_last_month',
       'discount_rate', 'clean_title', 'brand_extracted', 'category'],
      dtype='object')

In [4]:
df.isna().sum()

price               0
old_price           0
rating              0
review_count        0
sales_last_month    0
discount_rate       0
clean_title         0
brand_extracted     0
category            0
dtype: int64

In [5]:
df.to_csv("kozmetik_dataset_clean_1.csv", index=False)

In [6]:
df = pd.read_csv(
    "kozmetik_dataset_clean_1.csv",
    encoding="utf-8-sig"
)

In [8]:
df["price"] = pd.to_numeric(df["price"], errors="coerce")
df["old_price"] = pd.to_numeric(df["old_price"], errors="coerce")

print("Price ortalama:", df["price"].mean())
print("Old Price ortalama:", df["old_price"].mean())

def detect_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    
    return outliers, lower_bound, upper_bound

price_outliers, price_low, price_high = detect_outliers(df, "price")
print("\nPRICE outlier sayısı:", len(price_outliers))
print("PRICE sınırlar:", price_low, price_high)

old_price_outliers, old_low, old_high = detect_outliers(df, "old_price")
print("\nOLD_PRICE outlier sayısı:", len(old_price_outliers))
print("OLD_PRICE sınırlar:", old_low, old_high)

outliers_all = pd.concat([price_outliers, old_price_outliers]).drop_duplicates()

Price ortalama: 1613.0987550200803
Old Price ortalama: 550.0083887646394

PRICE outlier sayısı: 29
PRICE sınırlar: -644.9499999999998 1650.81

OLD_PRICE outlier sayısı: 35
OLD_PRICE sınırlar: -78.80999999999995 847.27

In [9]:
df["price"] = pd.to_numeric(df["price"], errors="coerce")
df["old_price"] = pd.to_numeric(df["old_price"], errors="coerce")

price_mean = df["price"].mean()
old_price_mean = df["old_price"].mean()

def get_bounds(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return lower, upper

price_low, price_high = get_bounds(df, "price")
old_low, old_high = get_bounds(df, "old_price")

df.loc[(df["price"] < price_low) | (df["price"] > price_high), "price"] = price_mean

df.loc[(df["old_price"] < old_low) | (df["old_price"] > old_high), "old_price"] = old_price_mean

df.loc[df["old_price"] > df["price"], "old_price"] = df["price"]

print("Price mean:", df["price"].mean())
print("Old Price mean:", df["old_price"].mean())

Price mean: 572.5011803035435
Old Price mean: 342.06064277792706

In [30]:
df["price"] = pd.to_numeric(df["price"], errors="coerce")
df["old_price"] = pd.to_numeric(df["old_price"], errors="coerce")

df["discount_rate"] = ((df["old_price"] - df["price"]) / df["old_price"]) * 100

df["discount_rate"] = df["discount_rate"].replace([np.inf, -np.inf], np.nan).fillna(0)

df["discount_rate"] = df["discount_rate"].round(2)

print(df[["price", "old_price", "discount_rate"]].head())

    price  old_price  discount_rate
0  355.00     355.00            0.0
1  284.90     284.90            0.0
2  350.95     350.95            0.0
3  254.90     254.90            0.0
4  499.00     499.00            0.0

In [31]:
df["price"] = df["price"].round(2)
df["old_price"] = df["old_price"].round(2)

In [32]:
df.head()

,price,old_price,rating,review_count,sales_last_month,discount_rate,clean_title,brand_extracted,category
0,355.00,355.00,4.3,102,287,0.0,golden rose longstay liquid matte lipstick no ...,Golden Rose,Makyaj
1,284.90,284.90,3.9,32,50,0.0,note cosmetics 3 in 1 healthy skin tinted mois...,Note Cosmetics,Cilt Bakımı
2,350.95,350.95,4.0,28,425,0.0,note cosmetics collagen concealer 01 kolajen i...,Note Cosmetics,Makyaj
3,254.90,254.90,4.4,74,80,0.0,note cosmetics mineral concealer 202 spf 15 go...,Note Cosmetics,Makyaj
4,499.00,499.00,4.3,13,500,0.0,l oreal paris telescopic maskara siyah,Lore,Makyaj

In [33]:
print(df[["price", "old_price"]].describe())

             price   old_price
count   249.000000  249.000000
mean    572.501325  342.060843
std     491.854501  173.439887
min      21.500000   21.500000
25%     215.960000  199.000000
50%     399.000000  340.000000
75%     789.900000  499.000000
max    1613.100000  789.900000

In [34]:
unique_ratings = df["rating"].unique()
print(unique_ratings)

[4.3 3.9 4.  4.4 4.7 4.5 4.6 4.2 5.  4.1 3.4 3.5 3.6 3.8 2.6 2.4 2.8 3.2
 2.  4.9 4.8 1.  3.  3.3 2.9 3.7]

In [35]:
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

df["rating"] = df["rating"].round(1)

print(df["rating"].unique())

[4.3 3.9 4.  4.4 4.7 4.5 4.6 4.2 5.  4.1 3.4 3.5 3.6 3.8 2.6 2.4 2.8 3.2
 2.  4.9 4.8 1.  3.  3.3 2.9 3.7]

In [36]:
df["review_count"] = pd.to_numeric(df["review_count"], errors="coerce")

df["review_count"] = df["review_count"].astype(int)

print(df["review_count"].describe())

count    249.000000
mean     102.277108
std      192.896365
min        1.000000
25%        3.000000
50%       32.000000
75%      102.000000
max      972.000000
Name: review_count, dtype: float64

In [37]:
df["review_count"] = df["review_count"].round(2)

In [38]:
df.to_csv("kozmetik_dataset_preprocessing_end.csv", index=False)